# Dependencies
markdown:         kramdown
##highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Bakertunes
tagline:          'More music than you can shake a stick at'
description:      'Bakertunes is a collection of the music composed and arranged by Sarah Baker, Composer in Residence for Services for Education Music Services and examiner for ABRSM.'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
  
timezone:         Europe/London
future:           true

paginate:         5
paginate_path:    "/_posts/page:num/"

sass:
  style:          compressed
  sass_dir:       assets/sass

google_analytics: UA-51920187-1

# Custom vars
# version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
  
plugins:          [jekyll-paginate]

# Collections
collections:
  pianomusic:
    output: true
    